server:
  port: 8888
  servlet:
    context-path: /lucene
spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /pages/
  datasource:
    url: jdbc:mysql://localhost:3306/msgdb?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      auto-commit: true
